#!/usr/bin/env bash
# Render every diagram source to SVG + PNG.
#
#   docs/diagrams/src/*.mmd    Mermaid, written by hand
#   docs/diagrams/src/*.dot    Graphviz, written by hand (when Mermaid can't express it)
#   docs/diagrams/build/*.mmd  Mermaid, generated by scripts/where_it_sits.py
#
# Outputs: docs/diagrams/out/<name>.svg and <name>.png, plus out/manifest.tsv,
# which records each source's sha256 so tests can tell when an image is stale.
# Exits 1 if any render fails or produces an empty file.
#
# PNG flags: --size 1800 -s 2 -b white -t neutral. mermaid-cli 12 removed -w
# ("error: unknown option '-w'"); --size caps the longest side at 1800 CSS px and
# -s 2 doubles the pixel density, so text stays sharp when zoomed.
set -euo pipefail

cd "$(dirname "$0")/.."

SRC=docs/diagrams/src
BUILD=docs/diagrams/build
OUT=docs/diagrams/out
CONFIG=scripts/mermaid-config.json
PY=.venv/bin/python

command -v mmdc >/dev/null || { echo "mmdc not found. Install: npm install -g @mermaid-js/mermaid-cli@12.0.0" >&2; exit 1; }
command -v dot >/dev/null || { echo "dot not found. Install: brew install graphviz" >&2; exit 1; }

mkdir -p "$OUT" "$BUILD"

# Regenerate the "where it sits" sources from the architecture diagram.
rm -f "$BUILD"/*.mmd
"$PY" scripts/where_it_sits.py >/dev/null

shopt -s nullglob
sources=("$SRC"/*.mmd "$SRC"/*.dot "$BUILD"/*.mmd)
if [ ${#sources[@]} -eq 0 ]; then
  echo "No diagram sources found in $SRC or $BUILD" >&2
  exit 1
fi

manifest_tmp=$(mktemp)
log=$(mktemp)
trap 'rm -f "$manifest_tmp" "$log"' EXIT
failures=0

printf '%-34s %-7s %10s %10s\n' "DIAGRAM" "STATUS" "SVG BYTES" "PNG BYTES"
printf '%-34s %-7s %10s %10s\n' "-------" "------" "---------" "---------"

for src in "${sources[@]}"; do
  file=$(basename "$src")
  name="${file%.*}"
  svg="$OUT/$name.svg"
  png="$OUT/$name.png"
  # Delete old outputs first, so a failed render can't leave a stale image
  # behind that still passes the "file exists and is non-empty" check.
  rm -f "$svg" "$png"
  status=ok

  case "$file" in
    *.mmd)
      mmdc -q -i "$src" -o "$svg" -c "$CONFIG" -t neutral -b white >"$log" 2>&1 \
        && mmdc -q -i "$src" -o "$png" -c "$CONFIG" -t neutral -b white --size 1800 -s 2 >>"$log" 2>&1 \
        || status=FAILED
      ;;
    *.dot)
      dot -Tsvg "$src" -o "$svg" >"$log" 2>&1 \
        && dot -Tpng -Gdpi=200 "$src" -o "$png" >>"$log" 2>&1 \
        || status=FAILED
      ;;
  esac

  for f in "$svg" "$png"; do
    [ -s "$f" ] || status=FAILED
  done

  svg_bytes=$( [ -f "$svg" ] && wc -c <"$svg" | tr -d ' ' || echo 0 )
  png_bytes=$( [ -f "$png" ] && wc -c <"$png" | tr -d ' ' || echo 0 )
  printf '%-34s %-7s %10s %10s\n' "$name" "$status" "$svg_bytes" "$png_bytes"

  if [ "$status" = ok ]; then
    sha=$(shasum -a 256 "$src" | cut -d' ' -f1)
    printf '%s\t%s\t%s\t%s\t%s\n' "$name" "$src" "$sha" "$svg_bytes" "$png_bytes" >>"$manifest_tmp"
  else
    failures=$((failures + 1))
    echo "  --- renderer output for $src ---" >&2
    sed 's/^/  /' "$log" >&2
  fi
done

if [ "$failures" -gt 0 ]; then
  echo "$failures diagram(s) failed to render; manifest not updated." >&2
  exit 1
fi

{
  printf 'name\tsource\tsha256\tsvg_bytes\tpng_bytes\n'
  sort "$manifest_tmp"
} >"$OUT/manifest.tsv"
echo "All ${#sources[@]} diagrams rendered. Manifest: $OUT/manifest.tsv"
