"""Generate the "Where it sits" diagram for each doc.

Every doc in docs/ opens with the system architecture, with that doc's component
highlighted. Copying the architecture diagram by hand into twenty files would
let them drift apart, so instead:

  source of truth  docs/diagrams/src/02-system-architecture.mmd
  what to mark     docs/diagrams/where-it-sits.tsv   (doc number -> node ids)
  generated        docs/diagrams/build/NN-where-it-sits.mmd  (gitignored)

scripts/render_diagrams.sh runs this first, then renders build/ like src/.
"""

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
ARCHITECTURE = REPO / "docs" / "diagrams" / "src" / "02-system-architecture.mmd"
TABLE = REPO / "docs" / "diagrams" / "where-it-sits.tsv"
BUILD = REPO / "docs" / "diagrams" / "build"

HIGHLIGHT_STYLE = "stroke:#dc2626,stroke-width:5px"
LEGEND_SUFFIX = "<br/>red border = the part this doc explains"

# A node definition starts a line: `id[...]`, `id(...)`, `id[(...)]`, `id{...}`.
NODE_DEF = re.compile(r"^\s*([A-Za-z][A-Za-z0-9_]*)\s*[\[\(\{>]", re.MULTILINE)
SUBGRAPH_DEF = re.compile(r"^\s*subgraph\s+([A-Za-z][A-Za-z0-9_]*)", re.MULTILINE)
LEGEND_LINE = re.compile(r'^(\s*legend\[".*?)("\].*)$', re.MULTILINE)


def node_ids(mermaid: str) -> set[str]:
    """Every node and subgraph id defined in a Mermaid flowchart."""
    return set(NODE_DEF.findall(mermaid)) | set(SUBGRAPH_DEF.findall(mermaid))


def read_table(path: Path) -> dict[str, list[str]]:
    """Parse where-it-sits.tsv: `NN<TAB>id1,id2` per line, '#' starts a comment."""
    table: dict[str, list[str]] = {}
    for lineno, raw in enumerate(path.read_text().splitlines(), start=1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split("\t")
        if len(parts) != 2 or not re.fullmatch(r"\d\d", parts[0]):
            raise ValueError(f"{path.name}:{lineno}: expected 'NN<TAB>id,id', got {raw!r}")
        doc, ids = parts
        if doc in table:
            raise ValueError(f"{path.name}:{lineno}: doc {doc} listed twice")
        table[doc] = [i.strip() for i in ids.split(",") if i.strip()]
    return table


def highlight(mermaid: str, ids: list[str]) -> str:
    """Return the diagram with `ids` given a thick red border and the legend extended.

    Raises ValueError on an unknown id: a typo must fail the build, not silently
    produce a diagram with nothing highlighted.
    """
    unknown = sorted(set(ids) - node_ids(mermaid))
    if unknown:
        raise ValueError(f"unknown node id(s) {unknown}; known: {sorted(node_ids(mermaid))}")
    if not ids:
        raise ValueError("nothing to highlight")
    marked, count = LEGEND_LINE.subn(lambda m: m.group(1) + LEGEND_SUFFIX + m.group(2), mermaid)
    if count != 1:
        raise ValueError(f"expected exactly one legend[\"...\"] node, found {count}")
    styles = "\n".join(f"    style {node} {HIGHLIGHT_STYLE}" for node in ids)
    return marked.rstrip("\n") + "\n\n    %% generated by scripts/where_it_sits.py\n" + styles + "\n"


def generate_all() -> dict[str, str]:
    """Map output file name -> generated Mermaid text, without writing anything."""
    architecture = ARCHITECTURE.read_text()
    return {
        f"{doc}-where-it-sits.mmd": highlight(architecture, ids)
        for doc, ids in read_table(TABLE).items()
    }


def main() -> int:
    BUILD.mkdir(parents=True, exist_ok=True)
    for name, text in generate_all().items():
        (BUILD / name).write_text(text)
        print(f"generated {BUILD.relative_to(REPO) / name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
